# Server Port
server.port=${SERVER_PORT:8080}

# MySQL Datasource Connection Config
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ivy_moda?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Mhun@1311}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Path to Firebase service account json key file (needed for Google Auth verify token)
# If running locally, you can specify this path, or omit it and use default credentials.
firebase.config-path=classpath:firebase-service-account.json
